// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResourceManager.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ResourceManager.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260118142106_EnableMultiTenancy")]
    partial class EnableMultiTenancy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ResourceManager.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MatriculeFiscal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumTel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Treated")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "18, Mohamed Triki, Ennasr 2 2001",
                            CreatedAt = new DateTime(2026, 1, 18, 14, 21, 4, 559, DateTimeKind.Utc).AddTicks(1698),
                            IsDeleted = false,
                            MatriculeFiscal = "1452393/C/MA/000",
                            Name = "Ste Xen Plus",
                            NumTel = "(+216) 28 227 508",
                            Treated = false,
                            UserId = ""
                        },
                        new
                        {
                            Id = 2,
                            Address = "Khaiereddine Bacha RET Bizerte Km5 2094",
                            CreatedAt = new DateTime(2026, 1, 18, 14, 21, 4, 559, DateTimeKind.Utc).AddTicks(1705),
                            IsDeleted = false,
                            MatriculeFiscal = "1422362/D/M/A/000",
                            Name = "Ste Om El Khir",
                            NumTel = "(+216) 20 953 633",
                            Treated = false,
                            UserId = ""
                        },
                        new
                        {
                            Id = 3,
                            Address = "Sidi Thabet, Km1",
                            CreatedAt = new DateTime(2026, 1, 18, 14, 21, 4, 559, DateTimeKind.Utc).AddTicks(1709),
                            IsDeleted = false,
                            MatriculeFiscal = "1203978/M/A/000",
                            Name = "Ste Le delice de Maman",
                            NumTel = "(+216) 70 553 682",
                            Treated = false,
                            UserId = ""
                        });
                });

            modelBuilder.Entity("ResourceManager.Models.DeliveryNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("DevisId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Treated")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("DevisId");

                    b.ToTable("DeliveryNotes");
                });

            modelBuilder.Entity("ResourceManager.Models.DeliveryNoteItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DeliveryNoteId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ItemTaxAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TaxRate")
                        .HasColumnType("numeric");

                    b.Property<int>("TotalEstimated")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryNoteId");

                    b.ToTable("DeliveryNoteItems");
                });

            modelBuilder.Entity("ResourceManager.Models.Devis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("SubTotal")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<bool>("Treated")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Devis");
                });

            modelBuilder.Entity("ResourceManager.Models.DevisItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DevisId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer");

                    b.Property<bool>("Tva")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("DevisId");

                    b.ToTable("DevisItems");
                });

            modelBuilder.Entity("ResourceManager.Models.Fournisseur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Treated")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Fournisseurs");
                });

            modelBuilder.Entity("ResourceManager.Models.FournisseurInvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("FournisseurId")
                        .HasColumnType("integer");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("integer");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FournisseurId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("FournisseurInvoices");
                });

            modelBuilder.Entity("ResourceManager.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("DevisId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("SubTotal")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TaxAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<bool>("Treated")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("DevisId")
                        .IsUnique();

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("ResourceManager.Models.InvoiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceItems");
                });

            modelBuilder.Entity("ResourceManager.Models.DeliveryNote", b =>
                {
                    b.HasOne("ResourceManager.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.HasOne("ResourceManager.Models.Devis", "Devis")
                        .WithMany("DeliveryNotes")
                        .HasForeignKey("DevisId");

                    b.Navigation("Client");

                    b.Navigation("Devis");
                });

            modelBuilder.Entity("ResourceManager.Models.DeliveryNoteItem", b =>
                {
                    b.HasOne("ResourceManager.Models.DeliveryNote", "DeliveryNote")
                        .WithMany("DeliveryNoteItems")
                        .HasForeignKey("DeliveryNoteId");

                    b.Navigation("DeliveryNote");
                });

            modelBuilder.Entity("ResourceManager.Models.Devis", b =>
                {
                    b.HasOne("ResourceManager.Models.Client", "Client")
                        .WithMany("Devis")
                        .HasForeignKey("ClientId");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("ResourceManager.Models.DevisItem", b =>
                {
                    b.HasOne("ResourceManager.Models.Devis", "Devis")
                        .WithMany("DevisItems")
                        .HasForeignKey("DevisId");

                    b.Navigation("Devis");
                });

            modelBuilder.Entity("ResourceManager.Models.FournisseurInvoice", b =>
                {
                    b.HasOne("ResourceManager.Models.Fournisseur", "Fournisseur")
                        .WithMany("FournisseurInvoices")
                        .HasForeignKey("FournisseurId");

                    b.HasOne("ResourceManager.Models.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId");

                    b.Navigation("Fournisseur");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("ResourceManager.Models.Invoice", b =>
                {
                    b.HasOne("ResourceManager.Models.Client", "Client")
                        .WithMany("Invoices")
                        .HasForeignKey("ClientId");

                    b.HasOne("ResourceManager.Models.Devis", "Devis")
                        .WithOne("Invoice")
                        .HasForeignKey("ResourceManager.Models.Invoice", "DevisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Devis");
                });

            modelBuilder.Entity("ResourceManager.Models.InvoiceItem", b =>
                {
                    b.HasOne("ResourceManager.Models.Invoice", "Invoice")
                        .WithMany("InvoiceItems")
                        .HasForeignKey("InvoiceId");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("ResourceManager.Models.Client", b =>
                {
                    b.Navigation("Devis");

                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("ResourceManager.Models.DeliveryNote", b =>
                {
                    b.Navigation("DeliveryNoteItems");
                });

            modelBuilder.Entity("ResourceManager.Models.Devis", b =>
                {
                    b.Navigation("DeliveryNotes");

                    b.Navigation("DevisItems");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("ResourceManager.Models.Fournisseur", b =>
                {
                    b.Navigation("FournisseurInvoices");
                });

            modelBuilder.Entity("ResourceManager.Models.Invoice", b =>
                {
                    b.Navigation("InvoiceItems");
                });
#pragma warning restore 612, 618
        }
    }
}
