#!/bin/bash
# ============================================
# ResourceManager - One-Time Server Setup
# ============================================
# Run this script on a FRESH Ubuntu VPS (22.04+) to prepare
# it for automated deployments via GitHub Actions.
#
# Usage:
#   ssh root@YOUR_VPS_IP
#   curl -sSL https://raw.githubusercontent.com/YOUR_USER/ResourceManager/main/scripts/server-setup.sh | bash
#   OR: copy this file and run: chmod +x server-setup.sh && sudo ./server-setup.sh
#
# After running, configure GitHub Secrets (see output at the end).
# ============================================

set -euo pipefail

# ── Colors for output ──
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}============================================${NC}"
echo -e "${BLUE} ResourceManager - Server Setup${NC}"
echo -e "${BLUE}============================================${NC}"
echo ""

# ── Must run as root ──
if [ "$(id -u)" -ne 0 ]; then
  echo -e "${RED}Error: This script must be run as root (use sudo)${NC}"
  exit 1
fi

DEPLOY_USER="deploy"
DEPLOY_PATH="$HOME/projects"
SSH_KEY_PATH="/home/${DEPLOY_USER}/.ssh"

# ============================================
# 1. System Updates & Dependencies
# ============================================
echo -e "${YELLOW}[1/7] Updating system packages...${NC}"
apt-get update -qq
apt-get upgrade -y -qq
apt-get install -y -qq curl wget git ufw fail2ban apt-transport-https ca-certificates gnupg lsb-release

# ============================================
# 2. Install Docker
# ============================================
echo -e "${YELLOW}[2/7] Installing Docker...${NC}"
if ! command -v docker &> /dev/null; then
  curl -fsSL https://get.docker.com | sh
  systemctl enable docker
  systemctl start docker
  echo -e "${GREEN}Docker installed successfully${NC}"
else
  echo -e "${GREEN}Docker already installed${NC}"
fi

# Verify Docker Compose is available (V2 is bundled with Docker now)
if docker compose version &> /dev/null; then
  echo -e "${GREEN}Docker Compose V2: $(docker compose version --short)${NC}"
else
  echo -e "${RED}Docker Compose not available. Install manually.${NC}"
  exit 1
fi

# ============================================
# 3. Create Deploy User
# ============================================
echo -e "${YELLOW}[3/7] Creating deploy user...${NC}"
if ! id "$DEPLOY_USER" &>/dev/null; then
  adduser --disabled-password --gecos "" "$DEPLOY_USER"
  echo -e "${GREEN}User '${DEPLOY_USER}' created${NC}"
else
  echo -e "${GREEN}User '${DEPLOY_USER}' already exists${NC}"
fi

# Add to docker group so they can run docker without sudo
usermod -aG docker "$DEPLOY_USER"

# ============================================
# 4. Setup SSH Key Authentication
# ============================================
echo -e "${YELLOW}[4/7] Setting up SSH key authentication...${NC}"
mkdir -p "$SSH_KEY_PATH"
touch "${SSH_KEY_PATH}/authorized_keys"
chown -R "${DEPLOY_USER}:${DEPLOY_USER}" "$SSH_KEY_PATH"
chmod 700 "$SSH_KEY_PATH"
chmod 600 "${SSH_KEY_PATH}/authorized_keys"

# Generate a deploy keypair if it doesn't exist
if [ ! -f "${SSH_KEY_PATH}/deploy_ed25519" ]; then
  ssh-keygen -t ed25519 -f "${SSH_KEY_PATH}/deploy_ed25519" -C "github-actions-deploy" -N ""
  cat "${SSH_KEY_PATH}/deploy_ed25519.pub" >> "${SSH_KEY_PATH}/authorized_keys"
  chown -R "${DEPLOY_USER}:${DEPLOY_USER}" "$SSH_KEY_PATH"
  echo -e "${GREEN}SSH deploy key generated${NC}"
else
  echo -e "${GREEN}SSH deploy key already exists${NC}"
fi

# ============================================
# 5. Create Application Directory
# ============================================
echo -e "${YELLOW}[5/7] Creating application directory...${NC}"
mkdir -p "${DEPLOY_PATH}/nginx"
chown -R "${DEPLOY_USER}:${DEPLOY_USER}" "$DEPLOY_PATH"

# Create .env from template if it doesn't exist
if [ ! -f "${DEPLOY_PATH}/.env" ]; then
  cat > "${DEPLOY_PATH}/.env" << 'ENVEOF'
# ══════════════════════════════════════════════
# ResourceManager — Production Environment
# ══════════════════════════════════════════════
# Generated by server-setup.sh — UPDATE ALL VALUES BELOW

# Database
POSTGRES_DB=resourcemanager
POSTGRES_USER=rmuser
POSTGRES_PASSWORD=CHANGE_ME_USE_OPENSSL_RAND

# Redis
REDIS_PASSWORD=CHANGE_ME_USE_OPENSSL_RAND

# JWT (min 32 chars)
JWT_KEY=CHANGE_ME_USE_OPENSSL_RAND_BASE64_48
JWT_ISSUER=ResourceManager
JWT_AUDIENCE=ResourceManager-Users
JWT_EXPIRATION=60

# Docker Images (updated automatically by deploy.yml)
API_IMAGE=ghcr.io/OWNER/resourcemanager-api:latest
WEB_IMAGE=ghcr.io/OWNER/resourcemanager-web:latest
NGINX_IMAGE=resourcemanager-nginx:latest

# CORS (your server IP or domain)
CORS_ORIGIN_1=http://YOUR_SERVER_IP
CORS_ORIGIN_2=http://YOUR_DOMAIN

# Ports
WEB_PORT=80
API_PORT=5000

# Google (optional — for email sending)
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GOOGLE_REFRESH_TOKEN=

# Supabase (optional — for file storage)
SUPABASE_URL=
SUPABASE_KEY=
ENVEOF

  # Generate random passwords
  POSTGRES_PW=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)
  REDIS_PW=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)
  JWT_SECRET=$(openssl rand -base64 48)

  sed -i "s|POSTGRES_PASSWORD=CHANGE_ME_USE_OPENSSL_RAND|POSTGRES_PASSWORD=${POSTGRES_PW}|" "${DEPLOY_PATH}/.env"
  sed -i "s|REDIS_PASSWORD=CHANGE_ME_USE_OPENSSL_RAND|REDIS_PASSWORD=${REDIS_PW}|" "${DEPLOY_PATH}/.env"
  sed -i "s|JWT_KEY=CHANGE_ME_USE_OPENSSL_RAND_BASE64_48|JWT_KEY=${JWT_SECRET}|" "${DEPLOY_PATH}/.env"

  chown "${DEPLOY_USER}:${DEPLOY_USER}" "${DEPLOY_PATH}/.env"
  chmod 600 "${DEPLOY_PATH}/.env"
  echo -e "${GREEN}.env created with random passwords${NC}"
else
  echo -e "${GREEN}.env already exists — not overwriting${NC}"
fi

# ============================================
# 6. Configure Firewall
# ============================================
echo -e "${YELLOW}[6/7] Configuring firewall (UFW)...${NC}"
ufw --force reset > /dev/null 2>&1
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp comment "SSH"
ufw allow 80/tcp comment "HTTP"
ufw allow 443/tcp comment "HTTPS (future)"
ufw --force enable
echo -e "${GREEN}Firewall configured: SSH(22), HTTP(80), HTTPS(443)${NC}"

# ============================================
# 7. Configure Fail2Ban
# ============================================
echo -e "${YELLOW}[7/7] Configuring Fail2Ban...${NC}"
systemctl enable fail2ban
systemctl start fail2ban
echo -e "${GREEN}Fail2Ban enabled${NC}"

# ============================================
# Summary
# ============================================
SERVER_IP=$(curl -s ifconfig.me 2>/dev/null || hostname -I | awk '{print $1}')

echo ""
echo -e "${GREEN}============================================${NC}"
echo -e "${GREEN} ✅ Server Setup Complete!${NC}"
echo -e "${GREEN}============================================${NC}"
echo ""
echo -e "${BLUE}Next Steps:${NC}"
echo ""
echo -e "${YELLOW}1. Copy the PRIVATE key below → GitHub Secret: VPS_SSH_KEY${NC}"
echo "   ─────────────────────────────────────────"
cat "${SSH_KEY_PATH}/deploy_ed25519"
echo "   ─────────────────────────────────────────"
echo ""
echo -e "${YELLOW}2. Set these GitHub Secrets (Settings → Secrets → Actions):${NC}"
echo "   ┌──────────────────┬──────────────────────────────┐"
echo "   │ Secret Name      │ Value                        │"
echo "   ├──────────────────┼──────────────────────────────┤"
echo "   │ VPS_HOST         │ ${SERVER_IP}                 │"
echo "   │ VPS_USER         │ ${DEPLOY_USER}               │"
echo "   │ VPS_SSH_KEY      │ (private key above)          │"
echo "   │ VPS_PORT         │ 22                           │"
echo "   │ GHCR_TOKEN       │ (GitHub PAT: read:packages)  │"
echo "   └──────────────────┴──────────────────────────────┘"
echo ""
echo -e "${YELLOW}3. Create a GitHub PAT for GHCR_TOKEN:${NC}"
echo "   GitHub → Settings → Developer settings → Personal Access Tokens"
echo "   → Tokens (classic) → Generate → Scope: read:packages"
echo ""
echo -e "${YELLOW}4. Edit .env with your actual values:${NC}"
echo "   nano ${DEPLOY_PATH}/.env"
echo "   - Update CORS_ORIGIN_1 with: http://${SERVER_IP}"
echo "   - Update API_IMAGE/WEB_IMAGE with your GitHub username"
echo "   - Add Google/Supabase keys if needed"
echo ""
echo -e "${YELLOW}5. Push to main branch → CI builds → deploy.yml auto-deploys${NC}"
echo ""
echo -e "${BLUE}Useful commands:${NC}"
echo "   ssh ${DEPLOY_USER}@${SERVER_IP}"
echo "   cd ${DEPLOY_PATH}"
echo "   docker compose -f docker-compose.yml -f docker-compose.prod.yml ps"
echo "   docker compose -f docker-compose.yml -f docker-compose.prod.yml logs -f api"
echo "   docker compose -f docker-compose.yml -f docker-compose.prod.yml down"
echo ""
