// Dummy data for the application
export const dummyInvoices = [
  {
    id: 1,
    number: 'INV-2024-001',
    invoiceNumber: 'INV-2024-001',
    date: '2024-01-15',
    dueDate: '2024-02-15',
    totalAmount: 1500.00,
    amountPaid: 1500.00,
    pendingAmount: 0,
    remainingAmount: 0,
    clientName: 'Acme Corporation',
    clientEmail: 'contact@acme.com',
    status: 'Paid',
    currency: 'USD',
    currencySymbol: '$',
  },
  {
    id: 2,
    number: 'INV-2024-002',
    invoiceNumber: 'INV-2024-002',
    date: '2024-01-20',
    dueDate: '2024-02-20',
    totalAmount: 2500.00,
    amountPaid: 1000.00,
    pendingAmount: 1500.00,
    remainingAmount: 1500.00,
    clientName: 'TechStart Inc',
    clientEmail: 'billing@techstart.com',
    status: 'PartiallyPaid',
    currency: 'USD',
    currencySymbol: '$',
  },
  {
    id: 3,
    number: 'INV-2024-003',
    invoiceNumber: 'INV-2024-003',
    date: '2024-02-01',
    dueDate: '2024-03-01',
    totalAmount: 3200.00,
    amountPaid: 0,
    pendingAmount: 3200.00,
    remainingAmount: 3200.00,
    clientName: 'Global Solutions Ltd',
    clientEmail: 'accounts@globalsolutions.com',
    status: 'Pending',
    currency: 'USD',
    currencySymbol: '$',
  },
  {
    id: 4,
    number: 'INV-2024-004',
    invoiceNumber: 'INV-2024-004',
    date: '2024-02-10',
    dueDate: '2024-01-10',
    totalAmount: 1800.00,
    amountPaid: 0,
    pendingAmount: 1800.00,
    remainingAmount: 1800.00,
    clientName: 'Innovation Hub',
    clientEmail: 'finance@innovationhub.com',
    status: 'Overdue',
    currency: 'USD',
    currencySymbol: '$',
  },
  {
    id: 5,
    number: 'INV-2024-005',
    invoiceNumber: 'INV-2024-005',
    date: '2024-02-15',
    dueDate: '2024-03-15',
    totalAmount: 4500.00,
    amountPaid: 4500.00,
    pendingAmount: 0,
    remainingAmount: 0,
    clientName: 'Digital Dynamics',
    clientEmail: 'billing@digitaldynamics.com',
    status: 'Paid',
    currency: 'USD',
    currencySymbol: '$',
  },
];

export const dummyArchivedInvoices = [
  {
    id: 101,
    number: 'INV-2023-045',
    invoiceNumber: 'INV-2023-045',
    date: '2023-11-15',
    dueDate: '2023-12-15',
    totalAmount: 2800.00,
    amountPaid: 2800.00,
    pendingAmount: 0,
    remainingAmount: 0,
    clientName: 'Legacy Corp',
    clientEmail: 'accounts@legacycorp.com',
    status: 'Paid',
    currency: 'USD',
    currencySymbol: '$',
    source: 'invoice' as const,
  },
  {
    id: 102,
    number: 'INV-2023-046',
    invoiceNumber: 'INV-2023-046',
    date: '2023-12-01',
    dueDate: '2024-01-01',
    totalAmount: 5400.00,
    amountPaid: 5400.00,
    pendingAmount: 0,
    remainingAmount: 0,
    clientName: 'Historical Client A',
    clientEmail: 'billing@historicala.com',
    status: 'Paid',
    currency: 'USD',
    currencySymbol: '$',
    source: 'historical' as const,
  },
];

export const availableDummyYears = [2024, 2023, 2022];

export const dummyClients = [
  {
    id: 1,
    name: 'Acme Corporation',
    email: 'contact@acme.com',
    phone: '+1 (555) 123-4567',
    address: '123 Business St, New York, NY 10001',
    totalInvoices: 5,
    totalAmount: 12500.00,
    status: 'Active',
  },
  {
    id: 2,
    name: 'TechStart Inc',
    email: 'billing@techstart.com',
    phone: '+1 (555) 234-5678',
    address: '456 Tech Ave, San Francisco, CA 94102',
    totalInvoices: 3,
    totalAmount: 8700.00,
    status: 'Active',
  },
  {
    id: 3,
    name: 'Global Solutions Ltd',
    email: 'accounts@globalsolutions.com',
    phone: '+44 20 7123 4567',
    address: '789 Corporate Blvd, London, UK',
    totalInvoices: 8,
    totalAmount: 25600.00,
    status: 'Active',
  },
  {
    id: 4,
    name: 'Innovation Hub',
    email: 'finance@innovationhub.com',
    phone: '+1 (555) 345-6789',
    address: '321 Innovation Way, Austin, TX 78701',
    totalInvoices: 2,
    totalAmount: 5400.00,
    status: 'Active',
  },
  {
    id: 5,
    name: 'Digital Dynamics',
    email: 'billing@digitaldynamics.com',
    phone: '+1 (555) 456-7890',
    address: '654 Digital Dr, Seattle, WA 98101',
    totalInvoices: 6,
    totalAmount: 18900.00,
    status: 'Active',
  },
];

export const dummySuppliers = [
  {
    id: 1,
    name: 'Office Supplies Co',
    email: 'sales@officesupplies.com',
    phone: '+1 (555) 111-2222',
    address: '100 Supply St, Chicago, IL 60601',
    totalInvoices: 12,
    totalAmount: 6500.00,
  },
  {
    id: 2,
    name: 'Tech Equipment Ltd',
    email: 'orders@techequipment.com',
    phone: '+1 (555) 222-3333',
    address: '200 Equipment Rd, Boston, MA 02101',
    totalInvoices: 8,
    totalAmount: 15200.00,
  },
  {
    id: 3,
    name: 'Industrial Materials Inc',
    email: 'contact@industrial.com',
    phone: '+1 (555) 333-4444',
    address: '300 Industrial Pkwy, Detroit, MI 48201',
    totalInvoices: 15,
    totalAmount: 32100.00,
  },
];

export const dummyProducts = [
  {
    id: 1,
    name: 'Web Development Service',
    description: 'Full-stack web development',
    price: 150.00,
    unit: 'hour',
    category: 'Service',
    sku: 'SRV-WEB-001',
  },
  {
    id: 2,
    name: 'Mobile App Development',
    description: 'iOS and Android app development',
    price: 175.00,
    unit: 'hour',
    category: 'Service',
    sku: 'SRV-MOB-001',
  },
  {
    id: 3,
    name: 'Consulting',
    description: 'Technical consulting services',
    price: 200.00,
    unit: 'hour',
    category: 'Service',
    sku: 'SRV-CON-001',
  },
  {
    id: 4,
    name: 'Cloud Hosting',
    description: 'Monthly cloud hosting service',
    price: 500.00,
    unit: 'month',
    category: 'Service',
    sku: 'SRV-HOST-001',
  },
];

export const dummyQuotes = [
  {
    id: 1,
    number: 'QT-2024-001',
    quoteNumber: 'QT-2024-001',
    date: '2024-02-01',
    validUntil: '2024-03-01',
    totalAmount: 5600.00,
    subTotal: 4800.00,
    taxAmount: 800.00,
    clientId: 1,
    clientName: 'Potential Client A',
    clientEmail: 'contact@potentiala.com',
    clientAddress: '123 Business St',
    status: 'Sent',
    treated: false,
    currency: 'USD',
    currencySymbol: '$',
    quoteItems: [
      {
        id: 1,
        description: 'Web Development Service',
        quantity: 20,
        price: 150.00,
        tva: true,
        vatRate: 0.19,
      },
      {
        id: 2,
        description: 'Consulting',
        quantity: 10,
        price: 200.00,
        tva: true,
        vatRate: 0.19,
      },
    ],
  },
  {
    id: 2,
    number: 'QT-2024-002',
    quoteNumber: 'QT-2024-002',
    date: '2024-02-05',
    validUntil: '2024-03-05',
    totalAmount: 3200.00,
    subTotal: 2800.00,
    taxAmount: 400.00,
    clientId: 2,
    clientName: 'Potential Client B',
    clientEmail: 'info@potentialb.com',
    status: 'Draft',
    treated: false,
    currency: 'USD',
    currencySymbol: '$',
    quoteItems: [
      {
        id: 3,
        description: 'Mobile App Development',
        quantity: 10,
        price: 175.00,
        tva: true,
        vatRate: 0.19,
      },
    ],
  },
  {
    id: 3,
    number: 'QT-2024-003',
    quoteNumber: 'QT-2024-003',
    date: '2024-02-10',
    validUntil: '2024-03-10',
    totalAmount: 8900.00,
    subTotal: 7500.00,
    taxAmount: 1400.00,
    clientId: 1,
    clientName: 'Acme Corporation',
    clientEmail: 'contact@acme.com',
    clientAddress: '123 Business St, New York, NY 10001',
    status: 'Accepted',
    treated: true,
    currency: 'USD',
    currencySymbol: '$',
    invoiceId: 1,
    quoteItems: [
      {
        id: 4,
        description: 'Cloud Hosting',
        quantity: 12,
        price: 500.00,
        tva: true,
        vatRate: 0.19,
      },
    ],
  },
];

export const dummyDeliveryNotes = [
  {
    id: 1,
    number: 'DN-2024-001',
    deliveryNoteNumber: 'DN-2024-001',
    date: '2024-03-01',
    clientId: 1,
    clientName: 'Acme Corporation',
    clientAddress: '123 Business St, New York, NY 10001',
    clientEmail: 'contact@acme.com',
    quoteId: 1,
    quoteNumber: 'QT-2024-001',
    invoiceId: 1,
    invoiceNumber: 'INV-2024-001',
    treated: true,
    itemsCount: 5,
    deliveryNoteItems: [
      { description: 'Web Development Service - 20 hours', quantity: 1 },
      { description: 'Consulting - 10 hours', quantity: 1 },
      { description: 'Project Documentation', quantity: 1 },
      { description: 'Training Session', quantity: 1 },
      { description: 'Technical Support', quantity: 1 },
    ],
  },
  {
    id: 2,
    number: 'DN-2024-002',
    deliveryNoteNumber: 'DN-2024-002',
    date: '2024-03-05',
    clientId: 2,
    clientName: 'TechStart Inc',
    clientAddress: '456 Tech Ave, San Francisco, CA 94102',
    clientEmail: 'billing@techstart.com',
    treated: false,
    itemsCount: 3,
    deliveryNoteItems: [
      { description: 'Mobile App Development', quantity: 1 },
      { description: 'UI/UX Design', quantity: 1 },
      { description: 'Testing & QA', quantity: 1 },
    ],
  },
  {
    id: 3,
    number: 'DN-2024-003',
    deliveryNoteNumber: 'DN-2024-003',
    date: '2024-03-10',
    clientId: 3,
    clientName: 'Global Solutions Ltd',
    clientAddress: '789 Corporate Blvd, London, UK',
    clientEmail: 'accounts@globalsolutions.com',
    quoteId: 3,
    quoteNumber: 'QT-2024-003',
    treated: false,
    itemsCount: 8,
    deliveryNoteItems: [
      { description: 'Cloud Hosting Setup', quantity: 1 },
      { description: 'Database Configuration', quantity: 1 },
      { description: 'Server Maintenance', quantity: 12 },
      { description: 'Security Audit', quantity: 1 },
      { description: 'Backup Solution', quantity: 1 },
      { description: 'Monitoring Dashboard', quantity: 1 },
      { description: 'SSL Certificates', quantity: 3 },
      { description: 'Technical Documentation', quantity: 1 },
    ],
  },
];

export const dummyExpenses = [
  {
    id: 1,
    description: 'Office Rent - March 2024',
    amount: 2500,
    date: '2024-03-01',
    category: 'rent',
    supplier: 'ABC Property Management',
    currency: 'USD',
    currencySymbol: '$',
    isRecurring: true,
    notes: 'Monthly office space rental',
    createdAt: '2024-03-01',
  },
  {
    id: 2,
    description: 'Internet & Phone Services',
    amount: 150,
    date: '2024-03-05',
    category: 'telecom',
    supplier: 'TelecomCo',
    currency: 'USD',
    currencySymbol: '$',
    isRecurring: true,
    notes: '',
    createdAt: '2024-03-05',
  },
  {
    id: 3,
    description: 'Office Supplies',
    amount: 320,
    date: '2024-03-10',
    category: 'office',
    supplier: 'Office Depot',
    currency: 'USD',
    currencySymbol: '$',
    isRecurring: false,
    notes: 'Printer paper, ink cartridges, pens',
    createdAt: '2024-03-10',
  },
  {
    id: 4,
    description: 'Software Subscriptions',
    amount: 499,
    date: '2024-03-15',
    category: 'subscription',
    supplier: 'Various',
    currency: 'USD',
    currencySymbol: '$',
    isRecurring: true,
    notes: 'GitHub, Figma, Adobe CC',
    createdAt: '2024-03-15',
  },
  {
    id: 5,
    description: 'Travel Expenses - Client Meeting',
    amount: 850,
    date: '2024-03-20',
    category: 'travel',
    supplier: 'Airlines & Hotels',
    currency: 'USD',
    currencySymbol: '$',
    isRecurring: false,
    notes: 'Round trip + 2 nights hotel',
    createdAt: '2024-03-20',
  },
  {
    id: 6,
    description: 'Office Rent - February 2024',
    amount: 2500,
    date: '2024-02-01',
    category: 'rent',
    supplier: 'ABC Property Management',
    currency: 'USD',
    currencySymbol: '$',
    isRecurring: true,
    notes: '',
    createdAt: '2024-02-01',
  },
  {
    id: 7,
    description: 'Marketing Campaign Q1',
    amount: 1500,
    date: '2024-02-15',
    category: 'marketing',
    supplier: 'Digital Ads Inc',
    currency: 'USD',
    currencySymbol: '$',
    isRecurring: false,
    notes: 'Google Ads + LinkedIn campaign',
    createdAt: '2024-02-15',
  },
  {
    id: 8,
    description: 'Office Rent - January 2024',
    amount: 2500,
    date: '2024-01-01',
    category: 'rent',
    supplier: 'ABC Property Management',
    currency: 'USD',
    currencySymbol: '$',
    isRecurring: true,
    notes: '',
    createdAt: '2024-01-01',
  },
  {
    id: 9,
    description: 'Insurance Premium Q1',
    amount: 1200,
    date: '2024-01-15',
    category: 'insurance',
    supplier: 'Business Insurance Co',
    currency: 'USD',
    currencySymbol: '$',
    isRecurring: false,
    notes: 'Quarterly premium',
    createdAt: '2024-01-15',
  },
  {
    id: 10,
    description: 'Server Maintenance',
    amount: 380,
    date: '2023-12-10',
    category: 'maintenance',
    supplier: 'Cloud Hosting Provider',
    currency: 'USD',
    currencySymbol: '$',
    isRecurring: false,
    notes: '',
    createdAt: '2023-12-10',
  },
];

export const dummySupplierInvoices = [
  {
    id: 1,
    fileName: 'supplier_inv_001.pdf',
    invoiceNumber: 'SUPP-2024-001',
    invoiceDate: '2024-03-01',
    dueDate: '2024-03-31',
    totalHT: 1200,
    totalTTC: 1440,
    tva: 240,
    supplierName: 'Tech Supplies Inc',
    supplierId: 1,
    amountPaid: 1440,
    remainingAmount: 0,
    paymentStatus: 'Paid',
    paymentCount: 1,
    currency: 'USD',
    currencySymbol: '$',
  },
  {
    id: 2,
    fileName: 'supplier_inv_002.pdf',
    invoiceNumber: 'SUPP-2024-002',
    invoiceDate: '2024-03-05',
    dueDate: '2024-04-05',
    totalHT: 3500,
    totalTTC: 4200,
    tva: 700,
    supplierName: 'Global Parts Ltd',
    supplierId: 2,
    amountPaid: 2000,
    remainingAmount: 2200,
    paymentStatus: 'Partial',
    paymentCount: 1,
    currency: 'USD',
    currencySymbol: '$',
  },
  {
    id: 3,
    fileName: 'supplier_inv_003.pdf',
    invoiceNumber: 'SUPP-2024-003',
    invoiceDate: '2024-03-10',
    dueDate: '2024-04-10',
    totalHT: 2800,
    totalTTC: 3360,
    tva: 560,
    supplierName: 'Office Solutions Co',
    supplierId: 3,
    amountPaid: 0,
    remainingAmount: 3360,
    paymentStatus: 'Pending',
    paymentCount: 0,
    currency: 'USD',
    currencySymbol: '$',
  },
];

export const dummyInventoryItems = [
  {
    id: 1,
    sku: 'LAPTOP-001',
    name: 'Dell Latitude 5420',
    category: 'Electronics',
    quantity: 15,
    minStock: 5,
    unit: 'pcs',
    unitPrice: 1200.00,
    totalValue: 18000.00,
    location: 'Warehouse A',
    status: 'In Stock',
  },
  {
    id: 2,
    sku: 'DESK-CHR-001',
    name: 'Office Chair Ergonomic',
    category: 'Furniture',
    quantity: 3,
    minStock: 5,
    unit: 'pcs',
    unitPrice: 350.00,
    totalValue: 1050.00,
    location: 'Warehouse B',
    status: 'Low Stock',
  },
  {
    id: 3,
    sku: 'CABLE-USB-C',
    name: 'USB-C Cable 2m',
    category: 'Accessories',
    quantity: 150,
    minStock: 50,
    unit: 'pcs',
    unitPrice: 15.00,
    totalValue: 2250.00,
    location: 'Warehouse A',
    status: 'In Stock',
  },
  {
    id: 4,
    sku: 'MON-27-4K',
    name: '27" 4K Monitor',
    category: 'Electronics',
    quantity: 8,
    minStock: 3,
    unit: 'pcs',
    unitPrice: 450.00,
    totalValue: 3600.00,
    location: 'Warehouse A',
    status: 'In Stock',
  },
];

export const dummyUsers = [
  {
    id: '1',
    email: 'admin@company.com',
    firstName: 'John',
    lastName: 'Admin',
    role: 'SuperAdmin',
    company: 'Main Company',
    companyId: 1,
  },
  {
    id: '2',
    email: 'manager@company.com',
    firstName: 'Sarah',
    lastName: 'Manager',
    role: 'Manager',
    company: 'Main Company',
    companyId: 1,
  },
  {
    id: '3',
    email: 'employee1@company.com',
    firstName: 'Mike',
    lastName: 'Johnson',
    role: 'Employee',
    company: 'Main Company',
    companyId: 1,
  },
  {
    id: '4',
    email: 'employee2@company.com',
    firstName: 'Emily',
    lastName: 'Davis',
    role: 'Employee',
    company: 'Main Company',
    companyId: 1,
  },
  {
    id: '5',
    email: 'manager2@company.com',
    firstName: 'Robert',
    lastName: 'Smith',
    role: 'Manager',
    company: 'Branch Office',
    companyId: 2,
  },
];

export const dummyDashboardStats = {
  /* multi-currency metadata */
  selectedCurrency: 'USD',
  availableCurrencies: ['USD'],
  availableYears: [2024, 2023],
  defaultCurrency: 'USD',
  selectedYear: 2024,

  totalRevenue: 45200.00,
  pendingInvoicesCount: 5,
  pendingInvoicesAmount: 8700.00,
  partiallyPaidCount: 2,
  partiallyPaidAmount: 3500.00,
  pendingPaymentsCount: 3,
  pendingPaymentsAmount: 5200.00,
  thisMonthRevenue: 9100.00,
  lastMonthRevenue: 8400.00,
  totalInvoiceCount: 15,
  paidInvoiceCount: 8,
  activeClients: 5,
  totalSuppliers: 3,
  supplierInvoices: 7,
  totalExpenses: 12450.00,
  growthDisplay: '+8.3%',
  growthPercentage: 8.3,
  isAllYearsMode: false,

  statusBreakdown: [
    { status: 'Paid', count: 8, amount: 28500.00 },
    { status: 'Pending', count: 5, amount: 8700.00 },
    { status: 'PartiallyPaid', count: 2, amount: 3500.00 },
  ],

  topClients: [
    { clientId: 1, clientName: 'Global Solutions Ltd', totalInvoices: 8, totalAmount: 25600.00, paidAmount: 22100.00 },
    { clientId: 2, clientName: 'Digital Dynamics', totalInvoices: 6, totalAmount: 18900.00, paidAmount: 15400.00 },
    { clientId: 3, clientName: 'Acme Corporation', totalInvoices: 5, totalAmount: 12500.00, paidAmount: 9800.00 },
    { clientId: 4, clientName: 'TechStart Inc', totalInvoices: 3, totalAmount: 8200.00, paidAmount: 5200.00 },
  ],

  revenueChart: [
    { month: 1, label: 'Jan', amount: 5200, count: 3 },
    { month: 2, label: 'Feb', amount: 6800, count: 2 },
    { month: 3, label: 'Mar', amount: 8500, count: 4 },
    { month: 4, label: 'Apr', amount: 7200, count: 2 },
    { month: 5, label: 'May', amount: 9100, count: 3 },
    { month: 6, label: 'Jun', amount: 8400, count: 1 },
  ],

  expenseChart: [
    { month: 1, label: 'Jan', amount: 1800, supplierCount: 2 },
    { month: 2, label: 'Feb', amount: 2100, supplierCount: 2 },
    { month: 3, label: 'Mar', amount: 2300, supplierCount: 3 },
    { month: 4, label: 'Apr', amount: 1950, supplierCount: 2 },
    { month: 5, label: 'May', amount: 2400, supplierCount: 3 },
    { month: 6, label: 'Jun', amount: 1900, supplierCount: 1 },
  ],

  mostSoldProducts: [
    { description: 'Web Development Service', totalQuantity: 12, totalAmount: 18500.00 },
    { description: 'UI/UX Design Package', totalQuantity: 8, totalAmount: 12400.00 },
    { description: 'SEO Consultation', totalQuantity: 15, totalAmount: 7500.00 },
    { description: 'Cloud Hosting (Annual)', totalQuantity: 5, totalAmount: 4500.00 },
    { description: 'Mobile App Development', totalQuantity: 3, totalAmount: 9600.00 },
  ],

  mostBoughtProducts: [
    { description: 'Server Hosting', totalQuantity: 6, totalAmount: 4200.00 },
    { description: 'Software Licenses', totalQuantity: 10, totalAmount: 3500.00 },
    { description: 'Office Supplies', totalQuantity: 25, totalAmount: 1800.00 },
    { description: 'Marketing Materials', totalQuantity: 8, totalAmount: 2200.00 },
  ],
};

export const dummyExpenseSummary = {
  totalAll: 12450.00,
  totalThisMonth: 2400.00,
  totalThisYear: 12450.00,
  count: 18,
  defaultCurrency: 'USD',
  byCategory: [
    { category: 'rent', currency: 'USD', total: 3600.00, count: 6 },
    { category: 'utilities', currency: 'USD', total: 1200.00, count: 6 },
    { category: 'office', currency: 'USD', total: 1800.00, count: 4 },
    { category: 'subscription', currency: 'USD', total: 2400.00, count: 6 },
    { category: 'marketing', currency: 'USD', total: 1500.00, count: 3 },
    { category: 'travel', currency: 'USD', total: 1950.00, count: 5 },
  ],
};

export const dummyRevenueSummary = {
  totalAllTime: 82500.00,
  selectedYearTotal: 45200.00,
  revenueByYear: [
    { year: 2024, total: 45200.00 },
    { year: 2023, total: 37300.00 },
  ],
};

export const dummyPurchasesSummary = {
  totalAllTime: 22800.00,
  selectedYearTotal: 12450.00,
  purchasesByYear: [
    { year: 2024, total: 12450.00 },
    { year: 2023, total: 10350.00 },
  ],
};

export const dummyInventoryReport = {
  totalProducts: 24,
  lowStockCount: 5,
  outOfStockCount: 2,
  totalStockValue: 22775.00,
  totalRetailValue: 28500.00,
  pendingPurchaseOrders: 3,
  recentMovements: [
    { type: 'in', count: 15 },
    { type: 'out', count: 8 },
  ],
};

export const dummyInventoryValuation = {
  totalStockValue: 22775.00,
  totalRetailValue: 28500.00,
  items: [
    { productServiceId: 1, productName: 'Web Development Service', currentStock: 50, defaultUnitPrice: 150.00, costPrice: 120.00, stockStatus: 'InStock' },
    { productServiceId: 2, productName: 'Mobile App Development', currentStock: 3, defaultUnitPrice: 175.00, costPrice: 140.00, stockStatus: 'LowStock' },
    { productServiceId: 3, productName: 'Consulting', currentStock: 0, defaultUnitPrice: 200.00, costPrice: 160.00, stockStatus: 'OutOfStock' },
    { productServiceId: 4, productName: 'Cloud Hosting', currentStock: 25, defaultUnitPrice: 500.00, costPrice: 400.00, stockStatus: 'InStock' },
    { productServiceId: 5, productName: 'USB-C Cable 2m', currentStock: 150, defaultUnitPrice: 15.00, costPrice: 8.00, stockStatus: 'Overstock' },
  ],
};

export const dummyStockAlerts = [
  { id: 1, productName: 'Printer Paper A4', currentStock: 5, minStock: 20, isResolved: false },
  { id: 2, productName: 'USB-C Cables', currentStock: 0, minStock: 10, isResolved: false },
  { id: 3, productName: 'Ink Cartridge Black', currentStock: 2, minStock: 5, isResolved: false },
  { id: 4, productName: 'Mouse Pad', currentStock: 3, minStock: 10, isResolved: true },
];

export const dummyStockLevels = {
  data: [
    { productServiceId: 1, productName: 'Web Development Service', currentStock: 50, reorderPoint: 10, stockValue: 7500.00, defaultUnitPrice: 150.00, stockStatus: 'InStock', isStockTracked: true },
    { productServiceId: 2, productName: 'Mobile App Development', currentStock: 3, reorderPoint: 5, stockValue: 525.00, defaultUnitPrice: 175.00, stockStatus: 'LowStock', isStockTracked: true },
    { productServiceId: 3, productName: 'Consulting', currentStock: 0, reorderPoint: 2, stockValue: 0.00, defaultUnitPrice: 200.00, stockStatus: 'OutOfStock', isStockTracked: true },
    { productServiceId: 4, productName: 'Cloud Hosting', currentStock: 25, reorderPoint: 5, stockValue: 12500.00, defaultUnitPrice: 500.00, stockStatus: 'InStock', isStockTracked: true },
    { productServiceId: 5, productName: 'USB-C Cable 2m', currentStock: 150, reorderPoint: 50, stockValue: 2250.00, defaultUnitPrice: 15.00, stockStatus: 'Overstock', isStockTracked: true },
  ],
  totalCount: 5,
  totalPages: 1,
};

export const dummyStockMovements = {
  data: [
    { id: 1, date: '2024-03-15', productName: 'Web Development Service', movementType: 'In', quantity: 10, stockAfter: 50, referenceNumber: 'PO-2024-001', notes: 'Restocking' },
    { id: 2, date: '2024-03-14', productName: 'Mobile App Development', movementType: 'Out', quantity: 5, stockAfter: 3, referenceNumber: 'INV-2024-005', notes: 'Sold to client' },
    { id: 3, date: '2024-03-10', productName: 'USB-C Cable 2m', movementType: 'In', quantity: 100, stockAfter: 150, referenceNumber: 'PO-2024-003', notes: 'Bulk order received' },
    { id: 4, date: '2024-03-05', productName: 'Consulting', movementType: 'Adjustment', quantity: 0, stockAfter: 0, referenceNumber: '', notes: 'Physical count correction' },
    { id: 5, date: '2024-02-28', productName: 'Cloud Hosting', movementType: 'In', quantity: 15, stockAfter: 25, referenceNumber: 'PO-2024-002', notes: '' },
    { id: 6, date: '2024-02-20', productName: 'Web Development Service', movementType: 'Out', quantity: 8, stockAfter: 40, referenceNumber: 'INV-2024-003', notes: 'Project delivery' },
    { id: 7, date: '2023-12-15', productName: 'USB-C Cable 2m', movementType: 'Return', quantity: 5, stockAfter: 55, referenceNumber: 'RET-2023-001', notes: 'Customer return' },
  ],
  totalCount: 7,
  totalPages: 1,
};

export const dummyProductServiceOptions = [
  { id: 1, name: 'Web Development Service', defaultUnitPrice: 150.00, isStockTracked: true },
  { id: 2, name: 'Mobile App Development', defaultUnitPrice: 175.00, isStockTracked: true },
  { id: 3, name: 'Consulting', defaultUnitPrice: 200.00, isStockTracked: true },
  { id: 4, name: 'Cloud Hosting', defaultUnitPrice: 500.00, isStockTracked: true },
  { id: 5, name: 'USB-C Cable 2m', defaultUnitPrice: 15.00, isStockTracked: true },
  { id: 6, name: 'SEO Consultation', defaultUnitPrice: 100.00, isStockTracked: false },
];

export const dummySettings = {
  companyName: 'My Company Ltd',
  companyAddress: '123 Business Street\nCity, State 12345\nCountry',
  companyTaxId: 'TAX123456789',
  companyPhone: '+1 (555) 123-4567',
  companyEmail: 'contact@mycompany.com',
  currency: 'USD',
  currencySymbol: '$',
  defaultVatRate: 20,
  primaryColor: '#065F46',
  secondaryColor: '#10B981',
};

export const dummyPurchaseOrders = [
  {
    id: 1,
    number: 'PO-2024-001',
    purchaseOrderNumber: 'PO-2024-001',
    date: '2024-03-01',
    expectedDeliveryDate: '2024-03-15',
    supplierId: 1,
    supplierName: 'Office Supplies Co',
    totalAmount: 2500.00,
    status: 'Sent',
    itemsCount: 5,
    currency: 'USD',
    currencySymbol: '$',
  },
  {
    id: 2,
    number: 'PO-2024-002',
    purchaseOrderNumber: 'PO-2024-002',
    date: '2024-03-05',
    expectedDeliveryDate: '2024-03-20',
    supplierId: 2,
    supplierName: 'Tech Equipment Ltd',
    totalAmount: 8900.00,
    status: 'PartiallyReceived',
    itemsCount: 8,
    currency: 'USD',
    currencySymbol: '$',
  },
  {
    id: 3,
    number: 'PO-2024-003',
    purchaseOrderNumber: 'PO-2024-003',
    date: '2024-03-10',
    expectedDeliveryDate: '2024-03-25',
    supplierId: 3,
    supplierName: 'Industrial Materials Inc',
    totalAmount: 15200.00,
    status: 'Received',
    itemsCount: 12,
    currency: 'USD',
    currencySymbol: '$',
  },
  {
    id: 4,
    number: 'PO-2024-004',
    purchaseOrderNumber: 'PO-2024-004',
    date: '2024-03-12',
    expectedDeliveryDate: null,
    supplierId: 1,
    supplierName: 'Office Supplies Co',
    totalAmount: 1200.00,
    status: 'Draft',
    itemsCount: 3,
    currency: 'USD',
    currencySymbol: '$',
  },
];