using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using ResourceManager.Data;
using ResourceManager.Models;
using System.Security.Claims;

namespace ResourceManager.Tests;

/// <summary>
/// Real integration tests using SQLite in-memory database with actual AppDbContext,
/// global query filters, Identity, and multi-tenant isolation.
/// These verify the actual SQL generated by EF Core — no fakes.
/// </summary>
public class FullStackIntegrationTests : IAsyncLifetime
{
    private SqliteConnection _connection = null!;
    private ServiceProvider _serviceProvider = null!;

    // Pre-seeded data available to all tests
    private Company _company1 = null!;
    private Company _company2 = null!;
    private ApplicationUser _adminUser = null!;

    public async Task InitializeAsync()
    {
        _connection = new SqliteConnection("DataSource=:memory:");
        _connection.Open();

        var services = new ServiceCollection();

        // Default (no-user) HTTP context
        services.AddSingleton<IHttpContextAccessor>(new HttpContextAccessor());

        services.AddDbContext<AppDbContext>(options =>
            options.UseSqlite(_connection));

        // Identity with DataProtection (required for token providers)
        services.AddDataProtection();
        services.AddIdentityCore<ApplicationUser>(options =>
        {
            options.Password.RequireDigit = false;
            options.Password.RequireLowercase = false;
            options.Password.RequireUppercase = false;
            options.Password.RequireNonAlphanumeric = false;
            options.Password.RequiredLength = 6;
        })
        .AddRoles<IdentityRole>()
        .AddEntityFrameworkStores<AppDbContext>()
        .AddDefaultTokenProviders();

        services.AddLogging();

        _serviceProvider = services.BuildServiceProvider();

        // Create the database schema
        using var scope = _serviceProvider.CreateScope();
        var context = scope.ServiceProvider.GetRequiredService<AppDbContext>();
        context.Database.EnsureCreated();

        // Seed roles
        var roleManager = scope.ServiceProvider.GetRequiredService<RoleManager<IdentityRole>>();
        foreach (var role in new[] { "SuperAdmin", "Manager", "FreeUser", "Employee" })
        {
            if (!await roleManager.RoleExistsAsync(role))
                await roleManager.CreateAsync(new IdentityRole(role));
        }

        // Seed companies (Company doesn't inherit Shared, so no FK auto-stamp issues)
        _company1 = new Company { Name = "Alpha Corp", Address = "A", TaxId = "A1", Phone = "+1", Email = "a@a.com", CreatedAt = DateTime.UtcNow };
        _company2 = new Company { Name = "Beta Corp", Address = "B", TaxId = "B1", Phone = "+2", Email = "b@b.com", CreatedAt = DateTime.UtcNow };
        context.Companies.Add(_company1);
        context.Companies.Add(_company2);
        await context.SaveChangesAsync();

        // Seed a real admin user in Company1 via UserManager
        var userManager = scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();
        _adminUser = new ApplicationUser
        {
            UserName = "admin@alpha.com",
            Email = "admin@alpha.com",
            CompanyId = _company1.Id,
            Profile = new UserProfile { FirstName = "Admin", LastName = "User", CreatedAt = DateTime.UtcNow }
        };
        var result = await userManager.CreateAsync(_adminUser, "Password123!");
        if (!result.Succeeded) throw new Exception($"User creation failed: {string.Join(", ", result.Errors.Select(e => e.Description))}");
        await userManager.AddToRoleAsync(_adminUser, "Manager");
    }

    public Task DisposeAsync()
    {
        _serviceProvider?.Dispose();
        _connection?.Dispose();
        return Task.CompletedTask;
    }

    /// <summary>
    /// Creates an AppDbContext scoped to a specific company and user.
    /// The user MUST exist in the database to avoid FK failures on CreatedByUserId.
    /// </summary>
    private AppDbContext CreateScopedContext(int companyId, string userId, string role = "Manager")
    {
        var claims = new List<Claim>
        {
            new(ClaimTypes.NameIdentifier, userId),
            new("CompanyId", companyId.ToString()),
            new(ClaimTypes.Role, role)
        };
        var identity = new ClaimsIdentity(claims, "Test");
        var principal = new ClaimsPrincipal(identity);

        var httpContext = new DefaultHttpContext { User = principal };
        var accessor = new HttpContextAccessor { HttpContext = httpContext };

        var options = new DbContextOptionsBuilder<AppDbContext>()
            .UseSqlite(_connection)
            .Options;

        return new AppDbContext(options, accessor);
    }

    /// <summary>
    /// Creates a SuperAdmin-scoped context (bypasses all global query filters).
    /// Uses the real admin user ID for audit stamps.
    /// </summary>
    private AppDbContext CreateSuperAdminContext()
    {
        var claims = new List<Claim>
        {
            new(ClaimTypes.NameIdentifier, _adminUser.Id),
            new(ClaimTypes.Role, "SuperAdmin")
        };
        var identity = new ClaimsIdentity(claims, "Test");
        var principal = new ClaimsPrincipal(identity);

        var httpContext = new DefaultHttpContext { User = principal };
        var accessor = new HttpContextAccessor { HttpContext = httpContext };

        var options = new DbContextOptionsBuilder<AppDbContext>()
            .UseSqlite(_connection)
            .Options;

        return new AppDbContext(options, accessor);
    }

    // ═══════════════════════════════════════════════════════════
    // TEST 1: Full Company + Manager + Employee Flow
    // ═══════════════════════════════════════════════════════════

    [Fact]
    public async Task FullFlow_CreateCompany_InviteManager_ManagerSeesOwnData()
    {
        // 1. Verify pre-seeded company exists
        using var saCtx = CreateSuperAdminContext();
        var company = await saCtx.Companies.FindAsync(_company1.Id);
        Assert.NotNull(company);
        Assert.Equal("Alpha Corp", company.Name);

        // 2. Admin user belongs to Company1
        var foundUser = await saCtx.Users.FirstOrDefaultAsync(u => u.Email == "admin@alpha.com");
        Assert.NotNull(foundUser);
        Assert.Equal(_company1.Id, foundUser.CompanyId);

        // 3. Manager creates a client in their company
        using var mgrCtx = CreateScopedContext(_company1.Id, _adminUser.Id, "Manager");
        var client = new Client
        {
            Name = "Client A",
            Address = "456 Client Rd",
            TaxId = "DEF456",
            Phone = "+216 71 111 111",
            CompanyId = _company1.Id,
            CreatedAt = DateTime.UtcNow
        };
        mgrCtx.Clients.Add(client);
        await mgrCtx.SaveChangesAsync();

        // Global query filter shows this client for Company1
        var clients = await mgrCtx.Clients.ToListAsync();
        Assert.Contains(clients, c => c.Name == "Client A");

        // 4. Manager creates an employee
        var userManager = _serviceProvider.GetRequiredService<UserManager<ApplicationUser>>();
        var employeeUser = new ApplicationUser
        {
            UserName = "employee@alpha.com",
            Email = "employee@alpha.com",
            CompanyId = _company1.Id,
            Profile = new UserProfile { FirstName = "Jane", LastName = "Employee", CreatedAt = DateTime.UtcNow }
        };
        var empResult = await userManager.CreateAsync(employeeUser, "Password123!");
        Assert.True(empResult.Succeeded, "Employee creation must succeed");
        await userManager.AddToRoleAsync(employeeUser, "Employee");

        // Employee sees the same client data
        using var empCtx = CreateScopedContext(_company1.Id, employeeUser.Id, "Employee");
        var empClients = await empCtx.Clients.ToListAsync();
        Assert.Contains(empClients, c => c.Name == "Client A");
    }

    // ═══════════════════════════════════════════════════════════
    // TEST 2: Multi-Tenant Isolation
    // ═══════════════════════════════════════════════════════════

    [Fact]
    public async Task MultiTenant_Company2CannotSeeCompany1Data()
    {
        // Company1 manager creates an invoice
        using var ctx1 = CreateScopedContext(_company1.Id, _adminUser.Id);
        var invoice = new Invoice
        {
            Number = "INV-ISO-001",
            Date = DateTime.UtcNow,
            CompanyId = _company1.Id,
            Status = "Pending",
            CreatedAt = DateTime.UtcNow,
            InvoiceItems = new List<InvoiceItem>
            {
                new InvoiceItem { Description = "Service", Quantity = 1, Price = 100m, Tva = false }
            },
            Tfiscal = 0m
        };
        invoice.CalculTotalAmount();
        ctx1.Invoices.Add(invoice);
        await ctx1.SaveChangesAsync();

        // Company 1 sees the invoice
        var invoices1 = await ctx1.Invoices.Where(i => i.Number == "INV-ISO-001").ToListAsync();
        Assert.Single(invoices1);

        // Create a Company2 user to test isolation
        var userManager = _serviceProvider.GetRequiredService<UserManager<ApplicationUser>>();
        var user2 = new ApplicationUser
        {
            UserName = "user@beta.com", Email = "user@beta.com",
            CompanyId = _company2.Id,
            Profile = new UserProfile { FirstName = "Beta", LastName = "User", CreatedAt = DateTime.UtcNow }
        };
        await userManager.CreateAsync(user2, "Password123!");

        // Company 2 CANNOT see Company 1's invoice
        using var ctx2 = CreateScopedContext(_company2.Id, user2.Id);
        var invoices2 = await ctx2.Invoices.Where(i => i.Number == "INV-ISO-001").ToListAsync();
        Assert.Empty(invoices2);
    }

    // ═══════════════════════════════════════════════════════════
    // TEST 3: Invoice Treated=true on Full Payment
    // ═══════════════════════════════════════════════════════════

    [Fact]
    public async Task Invoice_FullPayment_SetsTreatedTrue()
    {
        using var ctx = CreateScopedContext(_company1.Id, _adminUser.Id);

        var invoice = new Invoice
        {
            Number = "INV-TREAT-001",
            Date = DateTime.UtcNow,
            CompanyId = _company1.Id,
            Status = "Pending",
            CreatedAt = DateTime.UtcNow,
            Payments = new List<Payment>(),
            InvoiceItems = new List<InvoiceItem>
            {
                new InvoiceItem { Description = "Service", Quantity = 1, Price = 1000m, Tva = false }
            },
            Tfiscal = 0m
        };
        invoice.CalculTotalAmount();
        ctx.Invoices.Add(invoice);
        await ctx.SaveChangesAsync();

        Assert.Equal(1000m, invoice.TotalAmount);

        // Add payment matching TotalAmount
        var payment = new Payment
        {
            Amount = 1000m,
            PaymentDate = DateTime.UtcNow,
            Status = "Completed",
            InvoiceId = invoice.Id,
            CreatedAt = DateTime.UtcNow
        };
        ctx.Payments.Add(payment);

        // THE FIX being tested: Treated = true when fully paid
        var totalPaid = 1000m;
        if (totalPaid >= (invoice.TotalAmount ?? 0))
        {
            invoice.Status = "Paid";
            invoice.Treated = true;
            invoice.TreatedByUserId = _adminUser.Id;
            invoice.TreatedAt = DateTime.UtcNow;
        }
        await ctx.SaveChangesAsync();

        var saved = await ctx.Invoices.FirstOrDefaultAsync(i => i.Id == invoice.Id);
        Assert.NotNull(saved);
        Assert.True(saved.Treated, "Invoice must be Treated=true after full payment");
        Assert.Equal("Paid", saved.Status);
        Assert.NotNull(saved.TreatedAt);
    }

    // ═══════════════════════════════════════════════════════════
    // TEST 4: Archived Count with IgnoreQueryFilters + Imported Invoice
    // ═══════════════════════════════════════════════════════════

    [Fact]
    public async Task ArchivedCount_IncludesTreatedAndImportedInvoices()
    {
        using var ctx = CreateScopedContext(_company1.Id, _adminUser.Id);

        // Create 2 treated invoices + 1 untreated
        for (int i = 1; i <= 3; i++)
        {
            var inv = new Invoice
            {
                Number = $"INV-ARCH-{i:D3}",
                Date = new DateTime(2026, 1, 15, 0, 0, 0, DateTimeKind.Utc),
                CompanyId = _company1.Id,
                Status = i <= 2 ? "Paid" : "Pending",
                Treated = i <= 2,
                CreatedAt = DateTime.UtcNow,
                InvoiceItems = new List<InvoiceItem>
                {
                    new InvoiceItem { Description = $"Item {i}", Quantity = 1, Price = 500m * i, Tva = false }
                },
                Tfiscal = 0m
            };
            inv.CalculTotalAmount();
            ctx.Invoices.Add(inv);
        }

        // Also create an imported invoice record in the core table
        var importedInvoice = new Invoice
        {
            Number = "INV-ARCH-IMP-001",
            Date = new DateTime(2026, 1, 20, 0, 0, 0, DateTimeKind.Utc),
            CompanyId = _company1.Id,
            Status = "Pending",
            Category = "imported",
            CreatedAt = DateTime.UtcNow,
            InvoiceItems = new List<InvoiceItem>
            {
                new InvoiceItem { Description = "Imported Item", Quantity = 1, Price = 750m, Tva = false }
            },
            Tfiscal = 0m
        };
        importedInvoice.CalculTotalAmount();
        ctx.Invoices.Add(importedInvoice);
        await ctx.SaveChangesAsync();

        // ARCHIVED COUNT (same logic as InvoicesController.GetArchivedInvoicesCount):
        var archivedInvoiceCount = await ctx.Invoices
            .IgnoreQueryFilters()
            .AsNoTracking()
            .Where(i => i.CompanyId == _company1.Id
                     && i.Date.Year == 2026
                     && (i.Treated == true || i.Category == "imported"))
            .CountAsync();
        Assert.Equal(3, archivedInvoiceCount);
    }

    // ═══════════════════════════════════════════════════════════
    // TEST 5: Progress Calculation — Double Cast
    // ═══════════════════════════════════════════════════════════

    [Fact]
    public void PaymentProgress_DoubleCast_NoIntegerDivisionTruncation()
    {
        // THE BUG: integer division (1 / 3) = 0 in C#
        decimal amountPaid = 1m;
        decimal totalAmount = 3m;

        int brokenProgress = totalAmount > 0
            ? (int)((int)amountPaid / (int)totalAmount * 100)
            : 0;
        Assert.Equal(0, brokenProgress); // PROVES the bug

        // THE FIX: (double) cast BEFORE division
        double fixedProgress = totalAmount > 0
            ? Math.Min(100.0, (double)amountPaid / (double)totalAmount * 100.0)
            : 0.0;
        Assert.True(fixedProgress > 33.0 && fixedProgress < 34.0,
            $"Expected ~33.33%, got {fixedProgress}%");

        // Edge: zero total
        double zeroProgress = 0m > 0
            ? Math.Min(100.0, (double)0m / (double)0m * 100.0)
            : 0.0;
        Assert.Equal(0.0, zeroProgress);

        // Edge: fully paid
        double fullProgress = 1000m > 0
            ? Math.Min(100.0, (double)1000m / (double)1000m * 100.0)
            : 0.0;
        Assert.Equal(100.0, fullProgress);

        // Edge: overpaid (capped at 100)
        double overPaid = 500m > 0
            ? Math.Min(100.0, (double)600m / (double)500m * 100.0)
            : 0.0;
        Assert.Equal(100.0, overPaid);
    }

    // ═══════════════════════════════════════════════════════════
    // TEST 6: Notification Filter — "Pending" not "Due"
    // ═══════════════════════════════════════════════════════════

    [Fact]
    public async Task DuePayments_FilterByPending_NotDue()
    {
        using var ctx = CreateScopedContext(_company1.Id, _adminUser.Id);

        var invoice = new Invoice
        {
            Number = "INV-NOTIF-001",
            Date = DateTime.UtcNow,
            CompanyId = _company1.Id,
            Status = "Pending",
            CreatedAt = DateTime.UtcNow,
            InvoiceItems = new List<InvoiceItem>
            {
                new InvoiceItem { Description = "Consulting", Quantity = 1, Price = 500m, Tva = false }
            },
            Tfiscal = 0m
        };
        invoice.CalculTotalAmount();
        ctx.Invoices.Add(invoice);
        await ctx.SaveChangesAsync();

        // Past-due pending payment
        ctx.Payments.Add(new Payment
        {
            Amount = 200m,
            PaymentDate = DateTime.UtcNow.AddDays(-1),
            Status = "Pending",
            InvoiceId = invoice.Id,
            CreatedByUserId = _adminUser.Id,
            CreatedAt = DateTime.UtcNow
        });

        // Future pending payment (not yet due)
        ctx.Payments.Add(new Payment
        {
            Amount = 300m,
            PaymentDate = DateTime.UtcNow.AddDays(30),
            Status = "Pending",
            InvoiceId = invoice.Id,
            CreatedByUserId = _adminUser.Id,
            CreatedAt = DateTime.UtcNow
        });

        // Completed payment
        ctx.Payments.Add(new Payment
        {
            Amount = 100m,
            PaymentDate = DateTime.UtcNow.AddDays(-5),
            Status = "Completed",
            InvoiceId = invoice.Id,
            CreatedByUserId = _adminUser.Id,
            CreatedAt = DateTime.UtcNow
        });

        await ctx.SaveChangesAsync();

        // OLD BUG: Status == "Due" matches nothing
        var buggedQuery = await ctx.Payments
            .Where(p => p.CreatedByUserId == _adminUser.Id && p.Status == "Due")
            .CountAsync();
        Assert.Equal(0, buggedQuery);

        // FIX: Status == "Pending" AND PaymentDate <= now
        var fixedQuery = await ctx.Payments
            .Where(p => p.CreatedByUserId == _adminUser.Id
                     && p.Status == "Pending"
                     && p.PaymentDate <= DateTime.UtcNow)
            .CountAsync();
        Assert.Equal(1, fixedQuery);
    }

    // ═══════════════════════════════════════════════════════════
    // TEST 7: Imported Invoice isolation
    // ═══════════════════════════════════════════════════════════

    [Fact]
    public async Task ImportedInvoice_ImportSetsCompanyIdAndIsTenantIsolated()
    {
        using var ctx = CreateScopedContext(_company1.Id, _adminUser.Id);

        var importedInvoice = new Invoice
        {
            Number = "INV-IMP-ISO-001",
            Date = new DateTime(2025, 6, 15, 0, 0, 0, DateTimeKind.Utc),
            CompanyId = _company1.Id,
            Status = "Paid",
            Category = "imported",
            CreatedAt = DateTime.UtcNow,
            InvoiceItems = new List<InvoiceItem>
            {
                new InvoiceItem { Description = "Imported Service", Quantity = 1, Price = 5000m, Tva = false }
            },
            Tfiscal = 0m
        };
        importedInvoice.CalculTotalAmount();
        ctx.Invoices.Add(importedInvoice);
        await ctx.SaveChangesAsync();

        // Company1 sees it in imported invoices
        var importedInvoices = await ctx.Invoices
            .Where(i => i.Category == "imported")
            .ToListAsync();
        Assert.Contains(importedInvoices, i => i.Number == "INV-IMP-ISO-001");

        // Create Company2 user
        var userManager = _serviceProvider.GetRequiredService<UserManager<ApplicationUser>>();
        var user2 = new ApplicationUser
        {
            UserName = "hist@beta.com", Email = "hist@beta.com",
            CompanyId = _company2.Id,
            Profile = new UserProfile { FirstName = "B", LastName = "U", CreatedAt = DateTime.UtcNow }
        };
        await userManager.CreateAsync(user2, "Password123!");

        // Company2 cannot see Company1's imported invoice
        using var ctx2 = CreateScopedContext(_company2.Id, user2.Id);
        var otherImportedInvoices = await ctx2.Invoices
            .Where(i => i.Category == "imported")
            .ToListAsync();
        Assert.DoesNotContain(otherImportedInvoices, i => i.Number == "INV-IMP-ISO-001");
    }

    // ═══════════════════════════════════════════════════════════
    // TEST 8: Payment Deletion Resets Treated Flag
    // ═══════════════════════════════════════════════════════════

    [Fact]
    public async Task Invoice_PaymentDeleted_ResetsTreatedWhenNoLongerPaid()
    {
        using var ctx = CreateScopedContext(_company1.Id, _adminUser.Id);

        var invoice = new Invoice
        {
            Number = "INV-RESET-001",
            Date = DateTime.UtcNow,
            CompanyId = _company1.Id,
            Status = "Paid",
            Treated = true,
            TreatedByUserId = _adminUser.Id,
            TreatedAt = DateTime.UtcNow,
            CreatedAt = DateTime.UtcNow,
            InvoiceItems = new List<InvoiceItem>
            {
                new InvoiceItem { Description = "Service", Quantity = 1, Price = 500m, Tva = false }
            },
            Tfiscal = 0m,
            Payments = new List<Payment>
            {
                new Payment
                {
                    Amount = 500m,
                    PaymentDate = DateTime.UtcNow,
                    Status = "Completed",
                    CreatedByUserId = _adminUser.Id,
                    CreatedAt = DateTime.UtcNow
                }
            }
        };
        invoice.CalculTotalAmount();
        ctx.Invoices.Add(invoice);
        await ctx.SaveChangesAsync();

        Assert.True(invoice.Treated);

        // Delete the payment
        var payment = invoice.Payments!.First();
        ctx.Payments.Remove(payment);

        // Recalculate — same logic as InvoicesController.DeletePayment
        var remaining = invoice.Payments!.Where(p => p.Id != payment.Id).ToList();
        var totalPaidCompleted = remaining.Where(p => p.Status == "Completed").Sum(p => p.Amount);

        if (totalPaidCompleted < (invoice.TotalAmount ?? 0))
        {
            invoice.Status = totalPaidCompleted > 0 ? "PartiallyPaid" : "Pending";
            invoice.Treated = false;
            invoice.TreatedByUserId = null;
            invoice.TreatedAt = null;
        }
        await ctx.SaveChangesAsync();

        var updated = await ctx.Invoices.FirstOrDefaultAsync(i => i.Id == invoice.Id);
        Assert.NotNull(updated);
        Assert.False(updated.Treated, "Treated must be false after payment deletion");
        Assert.Equal("Pending", updated.Status);
        Assert.Null(updated.TreatedByUserId);
    }

    // ═══════════════════════════════════════════════════════════
    // TEST 9: Invitation Token Lifecycle
    // ═══════════════════════════════════════════════════════════

    [Fact]
    public async Task Invitation_CreateValidateComplete_FullLifecycle()
    {
        using var saCtx = CreateSuperAdminContext();

        // 1. Create invitation
        var token = Guid.NewGuid().ToString();
        var invitation = new ManagerInvitation
        {
            Id = Guid.NewGuid(),
            Email = "invited@newcorp.com",
            Token = token,
            ExpirationDate = DateTime.UtcNow.AddHours(48),
            IsUsed = false,
            CreatedAt = DateTime.UtcNow,
            CreatedByUserId = _adminUser.Id
        };
        saCtx.ManagerInvitations.Add(invitation);
        await saCtx.SaveChangesAsync();

        // 2. Validate token
        var found = await saCtx.ManagerInvitations
            .IgnoreQueryFilters()
            .FirstOrDefaultAsync(i => i.Token == token);
        Assert.NotNull(found);
        Assert.False(found.IsUsed);
        Assert.True(found.ExpirationDate > DateTime.UtcNow);

        // 3. Complete — create new company + user
        var newCompany = new Company
        {
            Name = "New Corp", Address = "New St", TaxId = "NEW1",
            Phone = "+216 00 000", Email = "invited@newcorp.com", CreatedAt = DateTime.UtcNow
        };
        saCtx.Companies.Add(newCompany);
        await saCtx.SaveChangesAsync();

        var userManager = _serviceProvider.GetRequiredService<UserManager<ApplicationUser>>();
        var newUser = new ApplicationUser
        {
            UserName = "invited@newcorp.com", Email = "invited@newcorp.com",
            CompanyId = newCompany.Id,
            Profile = new UserProfile { FirstName = "Invited", LastName = "Manager", CreatedAt = DateTime.UtcNow }
        };
        var result = await userManager.CreateAsync(newUser, "SecurePass1!");
        Assert.True(result.Succeeded);
        await userManager.AddToRoleAsync(newUser, "Manager");

        found.IsUsed = true;
        await saCtx.SaveChangesAsync();

        // 4. New manager creates company settings
        using var mgrCtx = CreateScopedContext(newCompany.Id, newUser.Id, "Manager");
        var settings = new CompanySettings
        {
            CompanyId = newCompany.Id,
            Currency = "TND",
            CurrencySymbol = "TND",
            InvoiceLanguage = "fr"
        };
        mgrCtx.CompanySettings.Add(settings);
        await mgrCtx.SaveChangesAsync();

        var savedSettings = await mgrCtx.CompanySettings.FirstOrDefaultAsync();
        Assert.NotNull(savedSettings);
        Assert.Equal(newCompany.Id, savedSettings.CompanyId);

        // 5. Used invitation should be marked
        var usedInvitation = await saCtx.ManagerInvitations
            .IgnoreQueryFilters()
            .FirstOrDefaultAsync(i => i.Token == token);
        Assert.NotNull(usedInvitation);
        Assert.True(usedInvitation.IsUsed);
    }

    // ═══════════════════════════════════════════════════════════
    // TEST 10: Manager Creates Employee — Same CompanyId
    // ═══════════════════════════════════════════════════════════

    [Fact]
    public async Task Manager_CreatesEmployee_InheritsSameCompanyId()
    {
        var userManager = _serviceProvider.GetRequiredService<UserManager<ApplicationUser>>();

        // Simulate register-manual: extract CompanyId from current user
        var currentUser = await userManager.FindByIdAsync(_adminUser.Id);
        Assert.NotNull(currentUser);
        var companyId = currentUser.CompanyId;

        // Create employee with SAME CompanyId
        var emp = new ApplicationUser
        {
            UserName = "emp10@alpha.com", Email = "emp10@alpha.com",
            CompanyId = companyId,
            Profile = new UserProfile { FirstName = "Emp", LastName = "Ten", CreatedAt = DateTime.UtcNow }
        };
        var empResult = await userManager.CreateAsync(emp, "Password123!");
        Assert.True(empResult.Succeeded, "Employee creation must succeed");
        await userManager.AddToRoleAsync(emp, "Employee");

        // Both users belong to Company1
        Assert.Equal(_company1.Id, emp.CompanyId);
        Assert.Equal(_company1.Id, _adminUser.CompanyId);

        // Data visibility: employee sees Company1 clients
        using var empCtx = CreateScopedContext(_company1.Id, emp.Id, "Employee");
        var clients = await empCtx.Clients.ToListAsync();
        Assert.NotNull(clients); // May be empty but no exception = scoped correctly
    }
}
